### ISSUE TITLE
pyglet==1.3.2 doesn't work with python 3.8

### ISSUE THREAD

**Issue by cshesse** [openai/procgen#3]
gym requires `pyglet==1.3.2`, so we'll probably just have to override that

```python -m procgen.interactive --env-name coinrun
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\pyglet\__init__.py", line 378, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'get_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\py38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\tools\miniconda3\envs\py38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\procgen\interactive.py", line 69, in <module>
    main()
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\procgen\interactive.py", line 64, in main
    ia = ProcgenInteractive(args.vision, env_name=args.env_name, **kwargs)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\procgen\interactive.py", line 21, in __init__
    super().__init__(env=env, sync=False, tps=15, display_info=True)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\procgen\interactive_base.py", line 73, in __init__
    display = pyglet.canvas.get_display()
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\pyglet\canvas\__init__.py", line 77, in get_display
    from pyglet.app import displays
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\pyglet\app\__init__.py", line 175, in <module>
    event_loop = EventLoop()
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\pyglet\app\base.py", line 119, in __init__
    self.clock = clock.get_default()
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\pyglet\__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "C:\tools\miniconda3\envs\py38\lib\site-packages\pyglet\clock.py", line 166, in <module>
    _default_time_function = time.clock
AttributeError: module 'time' has no attribute 'clock'```
